---
kind: pipeline
name: my-super-ci-pipeline

steps:
  - name: create-template
    image: lowess/preact-cli # (:latest)
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} test_ci
      - echo ${DRONE_REPO}#{$DRONE_COMMIT}

  - name: install
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm install

  - name: build
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm run build

  - name: preview
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm run build:preview

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: drone-ci
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}