---
kind: pipeline
name: my-super-ci-pipeline

steps:
  - name: create template
    image: lowess/preact-cli # (:latest)
    commands:
      - preact create template ${DRONE_REPO}#{$DRONE_COMMIT} test_ci
      - echo ${DRONE_REPO}#{$DRONE_COMMIT}
      - cd test_ci
      - echo "hell"

steps:
  - name: install
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm install

steps:
  - name: build
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm run build

steps:
  - name: preview
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm run build:preview