---
kind: pipeline
name: my-super-ci-pipeline

environment:
  BASE_URL: ${GITHUB_REPO_OWNER}.github.io/${DRONE_REPO_NAME}


steps:
  - name: create-template
    image: lowess/preact-cli # (:latest)
    commands:
      - preact create ${DRONE_REPO}#${DRONE_COMMIT} test_ci
      - echo ${DRONE_REPO}#{$DRONE_COMMIT}

  - name: install
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm install

  - name: build
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm run build

  - name: preview
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm run build:preview

  - name: slack
    image: plugins/slack
    settings:
      webhook: 
        from_secret: slack_webhook
      channel: drone-ci
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. bg badong
        {{else}}
          build {{build.number}} failed. nul nul nul badong.
        {{/success}}

  - name: publish  
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password: 
        from_secret: github_password
      pages_directory: test_ci/dist/