---
kind: pipeline
name: my-super-ci-pipeline

steps:
  - name: create-template
    image: lowess/preact-cli # (:latest)
    commands:
      - preact create ${DRONE_REPO}#{$DRONE_COMMIT} test_ci
      - echo ${DRONE_REPO}#{$DRONE_COMMIT}

  - name: install
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm install

  - name: build
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm run build

  - name: preview
    image: lowess/preact-cli # (:latest)
    commands:
      - cd test_ci
      - npm run build:preview